source 'https://github.com/CocoaPods/Specs.git'

target 'WPMediaPicker', :exclusive => true do
  pod "WPMediaPicker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "WPMediaPicker", :path => "../"

  
end
