# Opt in to new cops by default
AllCops:
  NewCops: enable

# Allow the Podspec filename to match the project
Naming/FileName:
  Exclude:
    - 'WordPress-Aztec-iOS.podspec'
    - 'WordPress-Editor-iOS.podspec'
    - 'Example/Carthage/Checkouts/Gridicons-iOS/Gridicons.podspec'
