# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#3.0.1
  # Common environment values to use with the `env` key.
  env: &common_env
    IMAGE_ID: xcode-15.4

# This is the default pipeline – it will build and test the app
steps:
  #################
  # Build and Test
  #################
  - label: "🧪 Build and Test"
    key: "test"
    command: |
      build_and_test_pod
    env: *common_env
    plugins: *common_plugins

  #################
  # Validate Podspecs
  #################
  - label: "🔬 Validate Podspecs"
    key: "validate"
    command: |
      validate_podspec --patch-cocoapods
    env: *common_env
    plugins: *common_plugins
    agents:
      queue: mac

  #################
  # Lint
  #################
  - label: "🧹 Lint"
    key: "lint"
    command: |
      lint_pod
    env: *common_env
    plugins: *common_plugins

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: "⬆️ Publish Aztec Podspec"
    key: "publish-aztec"
    command: .buildkite/publish-aztec-pod.sh
    env: *common_env
    plugins: *common_plugins
    depends_on:
      - "test"
      - "validate"
      - "lint"
    if: build.tag != null
    agents:
      queue: "mac"

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: "⬆️ Publish Editor Podspec"
    key: "publish-editor"
    command: .buildkite/publish-editor-pod.sh
    env: *common_env
    plugins: *common_plugins
    depends_on:
      - "test"
      - "validate"
      - "lint"
    if: build.tag != null
    agents:
      queue: "mac"
